import { Card } from 'src/game/entities/card.entity';
import { CardType } from 'src/game/types';

export const familiars: Partial<Card>[] = [
  {
    name: 'Кал Маркс',
    cost: 6,
    effect:
      'Может уничтожить и заменить карту на барахолке. Защита: может сбросить эту карту, чтобы избежать атак. Если сбросить, возьми 1 карту и передать эффект атаки против атакующего. Может уничтожить карту с руки.',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/familiar/IMG_8158_processed.png',
    damage: 0,
    power: 3,
    isAttack: false,
    isDefense: true,
    victoryPoints: 2,
    type: CardType.Familiar,
  },
  {
    name: 'Лорд Мышкинсон из Свирофолка',
    cost: 6,
    effect:
      'Атака: нанеси 2 урона каждому врагу за каждую тварь под твоим контролем и в твоей стопке сброса. Защита: можешь сбросить эту карту, чтобы избежать атаки. Если сбросить, возьми 1 карту и передать эффект атаки против атакующего.',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/familiar/IMG_8162_processed.png',
    damage: 2,
    power: 2,
    isAttack: true,
    isDefense: true,
    victoryPoints: 2,
    type: CardType.Familiar,
  },
  {
    name: 'Лобковое Отродье',
    cost: 6,
    effect:
      'Атака: нанеси выбранному врагу 7 урона. Защита: можешь сбросить эту карту, чтобы избежать атаки. Если сбросить, возьми 1 карту и передать эффект атаки против атакующего.',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/familiar/IMG_8163_processed.png',
    damage: 7,
    power: 2,
    isAttack: true,
    isDefense: true,
    victoryPoints: 2,
    type: CardType.Familiar,
  },
  {
    name: 'Монеточка',
    cost: 6,
    effect:
      'Если у тебя есть хотя бы 3 сброшенных в стопке сброса, ещё +3 мощи. Защита: можешь сбросить эту карту, чтобы избежать атаки. Если сбросить, возьми 1 карту и передать эффект атаки против атакующего.',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/familiar/IMG_8164_processed.png',
    damage: 0,
    power: 3,
    isAttack: false,
    isDefense: true,
    victoryPoints: 2,
    type: CardType.Familiar,
  },
  {
    name: 'Пых, Радужное Облако',
    cost: 6,
    effect:
      'Атака: каждый враг получает вылио половку. Защита: можешь сбросить эту карту, чтобы избежать атаки. Если сбросить, возьми 1 карту, а атакующий получает вылио половку.',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/familiar/IMG_8165_processed.png',
    damage: 0,
    power: 2,
    isAttack: true,
    isDefense: true,
    victoryPoints: 2,
    type: CardType.Familiar,
  },
  {
    name: 'Макгайвер, Жгучий Потрох',
    cost: 6,
    effect:
      'Атака: нанеси 2 урона каждому врагу за каждого волынщика под твоим контролем и в твоей стопке сброса. Защита: можешь сбросить эту карту, чтобы избежать атаки. Если сбросить, возьми 1 карту и передать эффект атаки против атакующего.',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/familiar/IMG_8160_processed.png',
    damage: 0,
    power: 2,
    isAttack: true,
    isDefense: true,
    victoryPoints: 2,
    type: CardType.Familiar,
  },
  {
    name: 'Елдун-Колдун',
    cost: 6,
    effect:
      'Если у тебя есть хотя бы 3 заклинания в стопке сброса, ещё +3 мощи. Защита: можешь сбросить эту карту, чтобы избежать атаки. Если сбросить, возьми 1 карту и передать эффект атаки против атакующего.',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/familiar/IMG_8169_processed.png',
    damage: 0,
    power: 3,
    isAttack: false,
    isDefense: true,
    victoryPoints: 2,
    type: CardType.Familiar,
  },
  {
    name: 'Сэр Соплейн Благословенный',
    cost: 6,
    effect:
      'Накрути 6 хизней. Защита: можешь сбросить эту карту, чтобы избежать атаки. Если сбросить, возьми 1 карту, накрути 3 хизни и передать эффект атаки против атакующего.',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/familiar/IMG_8170_processed.png',
    damage: 0,
    power: 2,
    isAttack: false,
    isDefense: true,
    victoryPoints: 2,
    type: CardType.Familiar,
  },
  {
    name: 'ШколотА!',
    cost: 6,
    effect:
      'В конце хода получи эту карту под изн колоды владельца. Защита: можешь сбросить эту карту, чтобы избежать атаки. Если сбросить, возьми 1 карту и передать эффект атаки против атакующего.',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/familiar/IMG_8168_processed.png',
    damage: 0,
    power: 2,
    isAttack: false,
    isDefense: true,
    victoryPoints: 2,
    type: CardType.Familiar,
  },
  {
    name: 'Угорелый Оруженосец',
    cost: 6,
    effect:
      'Посмотри 2 верхних карты своей колоды. Можешь уничтожить 1 из них. Защита: можешь сбросить эту карту, чтобы избежать атаки. Если сбросить, возьми 1 карту и передать эффект атаки против атакующего.',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/familiar/IMG_8167_processed.png',
    damage: 0,
    power: 2,
    isAttack: false,
    isDefense: true,
    victoryPoints: 2,
    type: CardType.Familiar,
  },
  {
    name: 'Асмодей, Демон Вечеринок',
    cost: 6,
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/familiar/IMG_8166_processed.png',
    damage: 0,
    power: 0,
    isAttack: false,
    isDefense: true,
    victoryPoints: 2,
    type: CardType.Familiar,
  },
  {
    name: 'Ведущий Оркганизатор',
    cost: 6,
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/familiar/IMG_8161_processed.png',
    damage: 0,
    power: 2,
    isAttack: false,
    isDefense: true,
    victoryPoints: 2,
    type: CardType.Familiar,
  },
];
