import { Card } from 'src/game/entities/card.entity';
import { CardType } from 'src/game/types';

export const legend: Partial<Card>[] = [
  {
    name: 'Однорукий одноглазый одномуд вуд',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    cost: 8,
    damage: 0,
    power: 1,
    imageUrl: '/legendaryDeck/IMG_8192_processed.png',
    isAttack: false,
    isDefense: false,
    victoryPoints: 4,
    type: CardType.Legend,
  },
  {
    name: 'Знак космоса',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    groupAttack: [],
    cost: 10,
    damage: 0,
    power: 0,
    imageUrl: '/legendaryDeck/IMG_8193_processed.png',
    isAttack: false,
    isDefense: false,
    victoryPoints: 5,
    type: CardType.Legend,
  },
  {
    name: 'Двойной отлизун, Демонический колдун',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    groupAttack: [],
    cost: 9,
    damage: 0,
    power: 0,
    imageUrl: '/legendaryDeck/IMG_8194_processed.png',
    isAttack: false,
    isDefense: false,
    victoryPoints: 5,
    type: CardType.Legend,
  },
  {
    name: 'Госпожа Бритта и её горячая киска',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    groupAttack: [],
    cost: 10,
    damage: 0,
    power: 2,
    imageUrl: '/legendaryDeck/IMG_8195_processed.png',
    isAttack: false,
    isDefense: false,
    victoryPoints: 5,
    type: CardType.Legend,
  },
  {
    name: 'Лорд Чернолорд, повелитель тьмы и котиков',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    groupAttack: [],
    cost: 11,
    damage: 0,
    power: 0,
    imageUrl: '/legendaryDeck/IMG_8196_processed.png',
    isAttack: false,
    isDefense: false,
    victoryPoints: 6,
    type: CardType.Legend,
  },
  {
    name: 'Константин, повелитель тьмы',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    groupAttack: [],
    cost: 10,
    damage: 0,
    power: 3,
    imageUrl: '/legendaryDeck/IMG_8197_processed.png',
    isAttack: false,
    isDefense: false,
    victoryPoints: 5,
    type: CardType.Legend,
  },
  {
    name: 'Кровомант лютонарк',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    groupAttack: [],
    cost: 9,
    damage: 0,
    power: 0,
    imageUrl: '/legendaryDeck/IMG_8198_processed.png',
    isAttack: false,
    isDefense: false,
    victoryPoints: 5,
    type: CardType.Legend,
  },
  {
    name: 'Череповец!!!',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    groupAttack: [],
    cost: 11,
    damage: 0,
    power: 0,
    imageUrl: '/legendaryDeck/IMG_8199_processed.png',
    isAttack: false,
    isDefense: false,
    victoryPoints: 6,
    type: CardType.Legend,
  },
  {
    name: 'Маша-расчленяша',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    groupAttack: [],
    cost: 12,
    damage: 0,
    power: 4,
    imageUrl: '/legendaryDeck/IMG_8200_processed.png',
    isAttack: true,
    isDefense: false,
    victoryPoints: 6,
    type: CardType.Legend,
  },
  {
    name: 'Бананамаг',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    groupAttack: [],
    cost: 9,
    damage: 0,
    power: 2,
    imageUrl: '/legendaryDeck/IMG_8201_processed.png',
    isAttack: false,
    isDefense: false,
    victoryPoints: 5,
    type: CardType.Legend,
  },
  {
    name: 'Бесплодие, рак лёгких, мучительная смерть',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    groupAttack: [],
    cost: 10,
    damage: 0,
    power: 2,
    imageUrl: '/legendaryDeck/IMG_8202_processed.png',
    isAttack: false,
    isDefense: false,
    victoryPoints: 5,
    type: CardType.Legend,
  },
  {
    name: 'Доктор выпил',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    groupAttack: [],
    cost: 12,
    damage: 0,
    power: 2,
    imageUrl: '/legendaryDeck/IMG_8203_processed.png',
    isAttack: false,
    isDefense: false,
    victoryPoints: 6,
    type: CardType.Legend,
  },
];
