import { Card } from 'src/game/entities/card.entity';
import {
  CardAttackProperty,
  CardDefenseProperty,
  CardProperty,
  CardType,
} from 'src/game/types';

export const mainDoubleDeck: Partial<Card>[] = [
  {
    name: 'Билли Адиш',
    effect: '',
    properties: [
      CardProperty.AddOnePower,
      CardProperty.IfItFirstCardToPlay,
      CardProperty.DiscardAllCards,
      CardProperty.DrawFourCards,
    ],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8204_processed.png',
    cost: 3,
    damage: 0,
    power: 1,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Wizard,
  },
  {
    name: 'Кровь-Кишки-Распидо',
    effect: '',
    properties: [
      CardProperty.IfHaveOverThreeDeadWizardDrawThreeCardsElseAddTwoPower,
    ],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8205_processed.png',
    cost: 5,
    damage: 0,
    power: 0,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Spell,
  },
  {
    name: 'Эпичные схватки',
    effect: '',
    properties: [CardProperty.AddThreePower],
    attackProperties: [
      CardAttackProperty.DealTwoDamageToSelectedEnemyForEveryDefenseCardInDiscard,
    ],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8206_processed.png',
    cost: 6,
    damage: 0,
    power: 3,
    victoryPoints: 2,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Spell,
  },
  {
    name: 'Нипутю!',
    effect: '',
    properties: [
      CardProperty.AddOnePower,
      CardProperty.PutNextBuyingCardOnTopOfDeck,
    ],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8207_processed.png',
    cost: 2,
    damage: 0,
    power: 1,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Spell,
  },
  {
    name: 'Двойняшки',
    effect: '',
    properties: [CardProperty.DrawTwoCard],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8209_processed.png',
    cost: 5,
    damage: 0,
    power: 0,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Creature,
  },
  {
    name: 'Виар, Колдун-виртуал',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [],
    defenseProperties: [
      CardDefenseProperty.DiscardCard,
      CardDefenseProperty.DrawTwoCardAndDiscardOne,
    ],
    imageUrl: '/mainDeck/IMG_8210_processed.png',
    cost: 5,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: false,
    isDefense: true,
    isSingleCard: false,
    type: CardType.Wizard,
  },
  {
    name: 'Рыцарь-сопленосец',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8211_processed.png',
    cost: 2,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Creature,
  },
  {
    name: 'Безумная Кошатница',
    effect: '',
    properties: [
      CardProperty.AddOnePower,
      CardProperty.YouAndSelectedEnemyDrawOneCard,
    ],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8212_processed.png',
    cost: 3,
    damage: 0,
    power: 1,
    victoryPoints: 1,
    isAttack: false,
    isDefense: true,
    isSingleCard: false,
    type: CardType.Wizard,
  },
  {
    name: 'Надмозг',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [
      CardAttackProperty.SelectedEnemyDiscardOneCardOfCostOverFiveIfEnemyEscapeAttackDealFiveDamage,
    ],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8214_processed.png',
    cost: 5,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Wizard,
  },
  {
    name: 'Змееволк Позорный',
    effect: '',
    properties: [CardProperty.AddTwoPower, CardProperty.GainTwoHealth],
    attackProperties: [
      CardAttackProperty.DealFiveDamageToEachEnemyWeakerThanYou,
    ],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8215_processed.png',
    cost: 5,
    damage: 5,
    power: 2,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Wizard,
  },
  {
    name: 'Золотая Немолодёжь',
    effect: '',
    properties: [CardProperty.GainOneHealthForEveryConstant],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8216_processed.png',
    cost: 3,
    damage: 0,
    power: 0,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    isPermanent: true,
    type: CardType.Treasure,
  },
  {
    name: 'Парево',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [],
    defenseProperties: [
      CardDefenseProperty.DiscardCard,
      CardDefenseProperty.DealTwoDamageToAttackerEnemy,
    ],
    imageUrl: '/mainDeck/IMG_8216_processed.png',
    cost: 4,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: false,
    isDefense: true,
    isSingleCard: false,
    type: CardType.Spell,
  },
  {
    name: 'Какой чудесный день',
    effect: '',
    properties: [CardProperty.DrawOneCard],
    attackProperties: [],
    defenseProperties: [
      CardDefenseProperty.DiscardCard,
      CardDefenseProperty.DrawOneCard,
      CardDefenseProperty.GainThreeHealth,
    ],
    imageUrl: '/mainDeck/IMG_8218_processed.png',
    cost: 3,
    damage: 0,
    power: 0,
    victoryPoints: 1,
    isAttack: false,
    isDefense: true,
    isSingleCard: false,
    type: CardType.Spell,
  },
  {
    name: 'Полное дерьмо',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [
      CardAttackProperty.EveryEnemyExpandTopCardOfTheirDeckYouCanDiscardThem,
    ],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8219_processed.png',
    cost: 3,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Treasure,
  },
  {
    name: 'Некростриптизёрши',
    effect: '',
    properties: [
      CardProperty.AddOnePower,
      CardProperty.AddOnePowerForEachDeadWizard,
    ],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8220_processed.png',
    cost: 3,
    damage: 0,
    power: 1,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Creature,
  },
  {
    name: 'Крысы-скейтеры с марса',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [],
    defenseProperties: [
      CardDefenseProperty.DiscardCard,
      CardDefenseProperty.PutOneCardFromHandOrDiscardToAttackerEnemyDiscard,
    ],
    imageUrl: '/mainDeck/IMG_8221_processed.png',
    cost: 4,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: false,
    isDefense: true,
    isSingleCard: false,
    type: CardType.Creature,
  },
  {
    name: 'Бедовая принцесса',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [
      CardAttackProperty.SelectedEnemyExpandTopCardOfHisDeckDealDamageAsItCost,
    ],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8222_processed.png',
    cost: 3,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Wizard,
  },
  {
    name: 'Раздраканус',
    effect: '',
    properties: [
      CardProperty.AddOnePower,
      CardProperty.CanDestroyCardFromDiscard,
    ],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8223_processed.png',
    cost: 3,
    damage: 0,
    power: 1,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Spell,
  },
  {
    name: 'Посох говнаря',
    effect: '',
    properties: [CardProperty.AddOnePower],
    attackProperties: [
      CardAttackProperty.DealThreeDamageToSelectedEnemy,
      CardAttackProperty.EnemyGetSluggishStick,
    ],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8224_processed.png',
    cost: 4,
    damage: 3,
    power: 1,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Treasure,
  },
  {
    name: 'Блеватико',
    effect: '',
    properties: [
      CardProperty.DrawOneCard,
      CardProperty.EachTimeYouGetOrBuyCardInTernPlayAttack,
    ],
    attackProperties: [
      CardAttackProperty.DealToSelectedEnemyDamageAsCostBoughtOrGotCard,
    ],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8225_processed.png',
    cost: 5,
    damage: 0,
    power: 0,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Spell,
  },
  {
    name: 'Фатализатор',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [
      CardAttackProperty.DealFourDamageWeakestEnemyIfHisDieNestingTwoDeadWizardSelectOneAndGiveToEnemy,
    ],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8226_processed.png',
    cost: 3,
    damage: 4,
    power: 2,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Creature,
  },
  {
    name: 'Миша, убийца единорогов',
    effect: '',
    properties: [CardProperty.CheckTopDeckCardRemoveGetOrHer],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8227_processed.png',
    cost: 4,
    damage: 0,
    power: 0,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Wizard,
  },
  {
    name: 'Мегафистинг',
    effect: '',
    properties: [CardProperty.DrawOneCard],
    attackProperties: [CardAttackProperty.DealSixDamageToLeftAndRightEnemy],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8228_processed.png',
    cost: 4,
    damage: 6,
    power: 0,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Spell,
  },
  {
    name: 'Орудия реп-битвы',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [
      CardAttackProperty.DealFourDamageEveryEnemyForEveryLegendInEnemyDiscardIfNoDamageCanDestroyCardInHand,
    ],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8229_processed.png',
    cost: 5,
    damage: 4,
    power: 2,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Treasure,
  },
  {
    name: 'Абракадабрадор',
    effect: '',
    properties: [CardProperty.DrawOneCard, CardProperty.GainTwoHealth],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8230_processed.png',
    cost: 2,
    damage: 0,
    power: 0,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Wizard,
  },
  {
    name: 'Боевая саксекира',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [CardAttackProperty.DealFiveDamageToLeftAndRightEnemy],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8231_processed.png',
    cost: 5,
    damage: 5,
    power: 2,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Treasure,
  },
  {
    name: 'Чегой-то',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [
      CardAttackProperty.DealThreeDamageToEveryEnemyForEveryPermanentCard,
    ],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8232_processed.png',
    cost: 5,
    damage: 3,
    power: 2,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Creature,
  },
  {
    name: 'Кровавый банщик',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [
      CardAttackProperty.SelectedEnemyExpandEveryCardOfHisHandDealDamageAsCostOfMostCostly,
    ],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8233_processed.png',
    cost: 4,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Creature,
  },
  {
    name: 'Кислотный дракон',
    effect: '',
    properties: [
      CardProperty.AddOnePower,
      CardProperty.CheckTopCardOfHisDeck,
      CardProperty.DrawOneCardOrReturnToDeck,
    ],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8234_processed.png',
    cost: 3,
    damage: 0,
    power: 1,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Creature,
  },
  {
    name: 'Генитальные гарпии',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [
      CardAttackProperty.DealTwoDamageEveryEnemyForEverySluggishStickInControlAndDiscardIfNoDamageDrawOneCard,
    ],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8235_processed.png',
    cost: 5,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Creature,
  },
  {
    name: 'Гнойный трепанатор',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [CardAttackProperty.EveryEnemyDiscardOneCard],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8236_processed.png',
    cost: 4,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Wizard,
  },
  {
    name: 'Секскалибур',
    effect: '',
    properties: [CardProperty.DrawAnyWizardCardFromDiscardOfAddTwoPower],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8237_processed.png',
    cost: 4,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Treasure,
  },
  {
    name: 'Шерстяная братва',
    effect: '',
    properties: [CardProperty.DrawAnyCreatureCardFromDiscardOfAddTwoPower],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8238_processed.png',
    cost: 4,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Spell,
  },
  {
    name: 'Жезл свинства',
    effect: '',
    properties: [CardProperty.DrawOneCard],
    attackProperties: [
      CardAttackProperty.GiveCardWithCostZeroFromHandOrDiscardToSelectedEnemyHand,
    ],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8239_processed.png',
    cost: 4,
    damage: 0,
    power: 0,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Treasure,
  },
  {
    name: 'Огнище',
    effect: '',
    properties: [CardProperty.AddThreePower],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8240_processed.png',
    cost: 5,
    damage: 0,
    power: 3,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Spell,
  },
  {
    name: 'Грешок-потрошок',
    effect: '',
    properties: [CardProperty.AddTwoPower],
    attackProperties: [CardAttackProperty.DealFiveDamageToSelectedEnemy],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8241_processed.png',
    cost: 3,
    damage: 5,
    power: 2,
    victoryPoints: 1,
    isAttack: true,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Spell,
  },
  {
    name: 'Карпатыч-сан',
    effect: '',
    properties: [CardProperty.DrawAnySpellCardFromDiscardOfAddTwoPower],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8242_processed.png',
    cost: 4,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Wizard,
  },
  {
    name: 'Язык роботов',
    effect: '',
    properties: [CardProperty.AddOnePower],
    attackProperties: [],
    defenseProperties: [
      CardDefenseProperty.DiscardCard,
      CardDefenseProperty.CanDestroyCardInHandOrDiscard,
    ],
    imageUrl: '/mainDeck/IMG_8243_processed.png',
    cost: 2,
    damage: 0,
    power: 1,
    victoryPoints: 1,
    isAttack: false,
    isDefense: true,
    isSingleCard: false,
    type: CardType.Treasure,
  },
  {
    name: 'Талисманы везунчика',
    effect: '',
    properties: [CardProperty.DrawAnyTreasureCardFromDiscardOfAddTwoPower],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/IMG_8244_processed.png',
    cost: 4,
    damage: 0,
    power: 2,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isSingleCard: false,
    type: CardType.Creature,
  },
];

export const getMainDoubleDeck = () => {
  return [...mainDoubleDeck, ...mainDoubleDeck];
};
