import { Card } from 'src/game/entities/card.entity';
import { CardProperty, CardType } from 'src/game/types';

export const place: Partial<Card>[] = [
  {
    name: 'Замок спрутобойни',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/single/place/IMG_8173_processed.png',
    cost: 5,
    damage: 0,
    power: 0,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isPermanent: true,
    type: CardType.Place,
  },
  {
    name: 'Грибучее болото',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/single/place/IMG_8174_processed.png',
    cost: 5,
    damage: 0,
    power: 0,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isPermanent: true,
    type: CardType.Place,
  },
  {
    name: 'Хоромы страсти',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/single/place/IMG_8175_processed.png',
    cost: 5,
    damage: 0,
    power: 0,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isPermanent: true,
    type: CardType.Place,
  },
  {
    name: 'Гора черепламени',
    effect: '',
    properties: [CardProperty.IfHaveFirstWizardDrawOneCard],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/single/place/IMG_8176_processed.png',
    cost: 5,
    damage: 0,
    power: 0,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isPermanent: true,
    type: CardType.Place,
  },
  {
    name: 'Шестёрочка',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/single/place/IMG_8177_processed.png',
    cost: 5,
    damage: 0,
    power: 0,
    victoryPoints: 1,
    isAttack: false,
    isDefense: false,
    isPermanent: true,
    type: CardType.Place,
  },
  {
    name: 'Арена крутагидона',
    effect: '',
    properties: [],
    attackProperties: [],
    defenseProperties: [],
    imageUrl: '/mainDeck/single/place/IMG_8178_processed.png',
    cost: 7,
    damage: 0,
    power: 0,
    victoryPoints: 2,
    isAttack: false,
    isDefense: false,
    isPermanent: true,
    type: CardType.Place,
  },
];
